yolo_model:

  config_file:
    name: yolov2-tiny-emoji.cfg
  weight_file:
    name: yolov2-tiny-emoji_10000.weights
  threshold:
    value: 0.9
  detection_classes:
    names:
      - monkey
      - surprised
      - thoughtful
      - like_a_boss
